openai:
  models:
    - gpt-4o
    - gpt-3.5-turbo
meta:
  models:
    - meta-llama/Llama-2-7b-chat-hf
    - meta-llama/Meta-Llama-3-8B-Instruct
gemini:
  models: []   # placeholders for the future
mistral:
  models: []   # placeholders for the future
claude:
  models: []
deepseek:
  models: []
