openai:
  models:
    - gpt-4o
    - gpt-3.5-turbo
meta:
  models:
    - meta-default
    - meta-v2
gemini:
  models: []   # placeholders for the future
mistral:
  models: []   # placeholders for the future
claude:
  models: []
deepseek:
  models: []
